# Generated by Django 4.1 on 2022-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
