# Generated by Django 4.1 on 2022-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_info_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Mail',
        ),
    ]
