# Generated by Django 4.1 on 2022-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_message_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='deleteFrom',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='mail',
            name='deleteTo',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
